# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# Artifacts: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

name: Maven Publish CI/CD

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:                        # Central + GPG secrets (add these in repo → Settings → Secrets → Actions)
  OSSRH_USERNAME:  ${{ secrets.OSSRH_USERNAME }}     # Central Portal access-key
  OSSRH_PASSWORD:  ${{ secrets.OSSRH_PASSWORD }}     # Central Portal secret
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}    # ASCII-armored private key
  GPG_PASSPHRASE:  ${{ secrets.GPG_PASSPHRASE }}     # pass-phrase (empty if none)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout JavaSteam with Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Clean & build
        run: ./gradlew clean build -x test
      - name: Publish SNAPSHOT to Sonatype
        run: ./gradlew publishToSonatype -x test
